name: hwf-app
static_sites:
  - name: hwf-app
    github:
      repo: hwf-app
      branch: main
    routes:
      - path: /
        source_dir: /
        index_document: index.html
        error_document: index.html
