name: hwf-app
region: fra
static_sites:
  - build_command: |
      npm install
      npm run build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: supdeocean/hwf.git
    name: hwf-app
    error_document: index.html
    routes:
      - path: /
        source_dir: /
        index_document: index.html
        error_document: index.html
