import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    //title
    'title.all': 'Aidons avec des meubles',
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.overview': 'Aidons avec des meubles',
    'dashboard.totalClients': 'Total Clients',
    'dashboard.activeVolunteers': 'Bénévoles Actifs',
    'dashboard.inventoryItems': 'Articles en Stock',
    'dashboard.pendingRequests': 'Requêtes en Cours',
    'dashboard.monthlyStats': 'Nouveaux Clients et Bénévoles par Mois',
    'dashboard.recentActivity': 'Activités Récentes',
    // Common
    'common.loading': 'Chargement...',
    'common.unknown': 'Inconnu',
    'common.request': 'Requête',
    'common.for': 'pour',
    'common.status': 'Statut',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.actions': 'Actions',
    'common.filters': 'Filtres',
    'common.areYouSure': 'Êtes-vous sûr?',
    'common.saving': 'Enregistrement...',
    'common.name': 'Nom',
    'common.description': 'Description',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.add': 'Ajouter',
    'common.create': 'Créer',
    'common.close': 'Fermer',
    'common.none': 'Aucun',
    'common.all': 'Tous',
    'common.select': 'Sélectionner',
    'common.submit': 'Soumettre',
    'common.confirm': 'Confirmer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.finish': 'Terminer',
    'common.optional': 'optionnel',
    'common.required': 'requis',
    'common.search': 'Rechercher',
    'common.new': 'Nouveau',
    'common.delete': 'Supprimer',
    'common.total': 'Total',
    'common.active': 'Actif',
    'common.completed': 'Terminé',
    'common.members': 'Membres',
    'common.skills': 'Compétences',
    'common.id': 'ID',
    'common.email': 'Courriel',
    'common.phone': 'Téléphone',
    'common.address': 'Adresse',
    'common.city': 'Ville',
    'common.adults': 'Adultes',
    'common.children': 'Enfants',
    'common.transportation': 'Transport',
    'common.housing': 'Logement',
    'common.origin': 'Origine',
    'common.availability': 'Disponibilité',
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.clients': 'Clients',
    'nav.volunteers': 'Bénévoles',
    'nav.teams': 'Équipes',
    'nav.inventory': 'Inventaire',
    'nav.categories': 'Catégories',
    'nav.requests': 'Requêtes',
    'nav.skills': 'Compétences',
    // Auth
    'auth.logout': 'Déconnexion',
    'auth.settings': 'Paramètres',
    'auth.administrator': 'Administrateur',
    'auth.volunteer': 'Bénévole',
    'auth.login': 'Connexion',
    'auth.email': 'Courriel',
    'auth.password': 'Mot de passe',
    'auth.signIn': 'Se connecter',
    'auth.signOut': 'Se déconnecter',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.invalidCredentials': 'Identifiants invalides',
    'auth.loginSuccess': 'Connexion réussie',
    'auth.loginError': 'Erreur de connexion',
    // Headers
    'header.backToClients': 'Retour aux Clients',
    'header.backToVolunteers': 'Retour aux Bénévoles',
    'header.backToInventory': 'Retour à l\'Inventaire',
    'header.backToRequests': 'Retour aux Requêtes',
    'header.backToTeams': 'Retour aux Équipes',
    'header.backHome': 'Retour à l\'accueil',
    // Actions
    'actions.addClient': 'Ajouter un Client',
    'actions.addVolunteer': 'Ajouter un Bénévole',
    'actions.addInventory': 'Ajouter un Article',
    'actions.addRequest': 'Ajouter une Requête',
    'actions.addTeam': 'Ajouter une Équipe',
    'actions.updateStatus': 'Mettre à jour le statut',
    'actions.cancel': 'Annuler',
    'actions.update': 'Mettre à jour',
    'actions.search': 'Rechercher',
    'actions.delete': 'Supprimer',
    'actions.save': 'Enregistrer',
    'actions.assign': 'Assigner',
    'actions.unassign': 'Désassigner',
    'actions.approve': 'Approuver',
    'actions.reject': 'Rejeter',
    'actions.complete': 'Terminer',
    'actions.schedule': 'Planifier',
    'actions.reschedule': 'Reprogrammer',
    'actions.export': 'Exporter',
    'actions.import': 'Importer',
    'actions.print': 'Imprimer',
    'actions.copy': 'Copier',
    'actions.move': 'Déplacer',
    // Pages
    'pages.clients.title': 'Clients',
    'pages.clients.addNew': 'Ajouter un Nouveau Client',
    'pages.clients.information': 'Informations du Client',
    'pages.clients.manage': 'Gérer les informations des clients',
    'pages.volunteers.title': 'Bénévoles',
    'pages.volunteers.manage': 'Gérez les informations et les assignations des bénévoles',
    'pages.volunteers.addNew': 'Ajouter un Nouveau Bénévole',
    'pages.volunteers.information': 'Informations du Bénévole',
    'pages.inventory.title': 'Inventaire',
    'pages.inventory.manage': 'Gérer les articles de dons et les niveaux de stock',
    'pages.inventory.addNew': 'Ajouter un Nouvel Article',
    'pages.inventory.information': 'Informations de l\'Article',
    'pages.requests.title': 'Requêtes',
    'pages.requests.addNew': 'Nouvelle Requête',
    'pages.requests.information': 'Détails de la Requête',
    'pages.requests.manage': 'Gérer les requêtes de dons',
    'pages.teams.title': 'Équipes',
    'pages.teams.manage': 'Gérer les équipes et leurs membres',
    'pages.teams.addNew': 'Nouvelle Équipe',
    'pages.teams.information': 'Informations de l\'Équipe',
    'pages.notFound.title': 'Page non trouvée',
    'pages.notFound.description': 'La page que vous recherchez n\'existe pas ou a été déplacée.',
    'pages.notFound.goHome': 'Retourner à l\'accueil',
    // Status
    'status.new': 'Nouveau',
    'status.inProgress': 'En cours',
    'status.processing': 'En traitement',
    'status.scheduled': 'Planifié',
    'status.completed': 'Terminé',
    'status.cancelled': 'Annulé',
    'status.active': 'Actif',
    'status.inactive': 'Inactif',
    'status.pending': 'En attente',
    'status.approved': 'Approuvé',
    'status.rejected': 'Rejeté',
    'status.draft': 'Brouillon',
    'status.published': 'Publié',
    'status.archived': 'Archivé',
    // Priority
    'priority.low': 'Basse',
    'priority.medium': 'Moyenne',
    'priority.high': 'Haute',
    'priority.urgent': 'Urgente',
    // Inventory
    'inventory.list': 'Liste d\'inventaire',
    'inventory.item': 'Article',
    'inventory.category': 'Catégorie',
    'inventory.condition': 'État',
    'inventory.quantity': 'Quantité',
    'inventory.location': 'Emplacement',
    'inventory.available': 'Disponible',
    'inventory.unavailable': 'Indisponible',
    'inventory.search': 'Rechercher dans l\'inventaire...',
    'inventory.noItems': 'Aucun article trouvé.',
    'inventory.errorLoading': 'Impossible de charger les articles de l\'inventaire',
    'inventory.itemDeleted': 'Article supprimé avec succès',
    'inventory.errorDeleting': 'Impossible de supprimer l\'article',
    'inventory.deleteConfirmation': 'Cette action ne peut pas être annulée. Cela supprimera définitivement l\'article d\'inventaire.',
    'inventory.itemAdded': 'Article ajouté avec succès',
    'inventory.itemUpdated': 'Article mis à jour avec succès',
    'inventory.errorAdding': 'Erreur lors de l\'ajout de l\'article',
    'inventory.errorUpdating': 'Erreur lors de la mise à jour de l\'article',
    // Categories
    'categories.manage': 'Gérer les catégories d\'inventaire pour une meilleure organisation',
    'categories.list': 'Liste des catégories',
    'categories.name': 'Nom de la catégorie',
    'categories.description': 'Description',
    'categories.addNew': 'Nouvelle catégorie',
    'categories.search': 'Rechercher des catégories...',
    'categories.noResults': 'Aucune catégorie trouvée.',
    'categories.errorLoading': 'Impossible de charger les catégories',
    'categories.deleted': 'Catégorie supprimée avec succès',
    'categories.errorDeleting': 'Impossible de supprimer la catégorie. Elle est peut-être utilisée par des articles d\'inventaire.',
    'categories.deleteTitle': 'Supprimer la catégorie',
    'categories.deleteConfirmation': 'Êtes-vous sûr de vouloir supprimer cette catégorie? Cette action ne peut pas être annulée.',
    'categories.delete': 'Supprimer la catégorie',
    'categories.information': 'Informations de la catégorie',
    'categories.addDescription': 'Ajoutez une nouvelle catégorie pour organiser votre inventaire',
    'categories.namePlaceholder': 'Entrez le nom de la catégorie',
    'categories.descriptionPlaceholder': 'Entrez la description de la catégorie',
    'categories.addSuccess': 'Catégorie ajoutée avec succès',
    'categories.errorAdding': 'Erreur lors de l\'ajout de la catégorie',
    // Client fields
    'client.firstName': 'Prénom',
    'client.lastName': 'Nom de famille',
    'client.email': 'Courriel',
    'client.phone': 'Téléphone',
    'client.address': 'Adresse',
    'client.city': 'Ville',
    'client.postalCode': 'Code postal',
    'client.languagesSpoken': 'Langues parlées',
    'client.countryOfOrigin': 'Pays d\'origine',
    'client.statusInCanada': 'Statut au Canada',
    'client.housingType': 'Type de logement',
    'client.hasTransportation': 'Possède un transport',
    'client.numberOfAdults': 'Nombre d\'adultes',
    'client.numberOfChildren': 'Nombre d\'enfants',
    'client.childrenAges': 'Âges des enfants',
    'client.referenceOrganization': 'Organisme de référence',
    'client.refClient': 'Client référent',
    'client.notes': 'Notes',
    'client.createdAt': 'Date de création',
    'client.updatedAt': 'Dernière modification',
    'client.addSuccess': 'Client ajouté avec succès',
    'client.updateSuccess': 'Client mis à jour avec succès',
    'client.deleteSuccess': 'Client supprimé avec succès',
    'client.errorAdding': 'Erreur lors de l\'ajout du client',
    'client.errorUpdating': 'Erreur lors de la mise à jour du client',
    'client.errorDeleting': 'Erreur lors de la suppression du client',
    'client.searchClient': 'Rechercher un client...',
    'client.noClientFound': 'Aucun client trouvé',
    'client.details': 'Détails du client',
    'client.contactInformation': 'Informations de contact',
    'client.householdInformation': 'Informations du ménage',
    'client.demographics': 'Démographie',
    'client.speaksLanguages': 'Parle',
    'client.fromCountry': 'De',
    'client.backToClients': 'Retour aux Clients',
    'client.editClient': 'Modifier',
    'client.deleteClient': 'Supprimer',
    'client.directory': 'Répertoire des clients',
    'client.searchClients': 'Rechercher des clients...',
    'client.noResults': 'Aucun client trouvé',
    'client.loading': 'Chargement des clients...',
    'client.select': 'Sélectionner un client',
    'client.selectClient': 'Sélectionner un client...',
    // Volunteer fields
    'volunteer.firstName': 'Prénom',
    'volunteer.lastName': 'Nom de famille',
    'volunteer.email': 'Courriel',
    'volunteer.phone': 'Téléphone',
    'volunteer.address': 'Adresse',
    'volunteer.city': 'Ville',
    'volunteer.postalCode': 'Code postal',
    'volunteer.skills': 'Compétences',
    'volunteer.availability': 'Disponibilité',
    'volunteer.notes': 'Notes',
    'volunteer.status': 'Statut',
    'volunteer.joinDate': 'Date d\'adhésion',
    'volunteer.addSuccess': 'Bénévole ajouté avec succès',
    'volunteer.updateSuccess': 'Bénévole mis à jour avec succès',
    'volunteer.deleteSuccess': 'Bénévole supprimé avec succès',
    'volunteer.errorAdding': 'Erreur lors de l\'ajout du bénévole',
    'volunteer.errorUpdating': 'Erreur lors de la mise à jour du bénévole',
    'volunteer.errorDeleting': 'Erreur lors de la suppression du bénévole',
    'volunteer.searchVolunteer': 'Rechercher un bénévole...',
    'volunteer.noVolunteerFound': 'Aucun bénévole trouvé',
    'volunteer.name': 'Nom',
    'volunteer.noResults': 'Aucun bénévole trouvé',
    'volunteer.loading': 'Chargement des bénévoles...',
    'volunteer.select': 'Sélectionner un bénévole',
    'volunteer.selectVolunteer': 'Sélectionner un bénévole...',
    // Team fields
    'team.name': 'Nom de l\'équipe',
    'team.description': 'Description',
    'team.members': 'Membres',
    'team.leader': 'Chef d\'équipe',
    'team.skills': 'Compétences',
    'team.status': 'Statut',
    'team.createdAt': 'Date de création',
    'team.addSuccess': 'Équipe ajoutée avec succès',
    'team.updateSuccess': 'Équipe mise à jour avec succès',
    'team.deleteSuccess': 'Équipe supprimée avec succès',
    'team.errorAdding': 'Erreur lors de l\'ajout de l\'équipe',
    'team.errorUpdating': 'Erreur lors de la mise à jour de l\'équipe',
    'team.errorDeleting': 'Erreur lors de la suppression de l\'équipe',
    'team.totalTeams': 'Total Équipes',
    'team.teamMembers': 'Membres d\'équipe',
    'team.activeRequests': 'Requêtes Actives',
    'team.completedRequests': 'Requêtes Terminées',
    'team.list': 'Liste des équipes',
    'team.searchTeams': 'Rechercher des équipes...',
    'team.teamName': 'Nom de l\'équipe',
    'team.newTeam': 'Nouvelle Équipe',
    'team.noResults': 'Aucune équipe trouvée',
    'team.loading': 'Chargement des équipes...',
    'team.selectTeams': 'Sélectionner des équipes...',
    'team.searchTeam': 'Rechercher une équipe...',
    'team.teamsSelected': 'équipe(s) sélectionnée(s)',
    'team.noTeamFound': 'Aucune équipe trouvée',
    'team.atLeastOneTeam': 'Au moins une équipe requise',
    // Status in Canada
    'status.permanentResident': 'Résident permanent',
    'status.refugee': 'Réfugié',
    'status.studentVisa': 'Visa étudiant',
    'status.temporaryResident': 'Résident temporaire',
    // Housing types
    'housing.apartment': 'Appartement',
    'housing.house': 'Maison',
    'housing.townhouse': 'Maison en rangée',
    'housing.basementApartment': 'Appartement au sous-sol',
    'housing.temporary': 'Temporaire',
    // Request fields
    'request.client': 'Client',
    'request.team': 'Équipe',
    'request.teams': 'Équipes',
    'request.volunteer': 'Bénévole',
    'request.priority': 'Priorité',
    'request.status': 'Statut',
    'request.location': 'Adresse de livraison',
    'request.description': 'Description',
    'request.details': 'Détails de la requête',
    'request.products': 'Sélection des produits',
    'request.selectTeams': 'Sélectionner des équipes...',
    'request.selectVolunteer': 'Sélectionner un bénévole...',
    'request.selectClient': 'Sélectionner un client...',
    'request.selectPriority': 'Sélectionner une priorité',
    'request.selectStatus': 'Sélectionner un statut',
    'request.enterLocation': 'Entrer l\'adresse',
    'request.enterDescription': 'Entrer les détails de la requête',
    'request.continueProducts': 'Continuer vers la sélection de produits',
    'request.backToDetails': 'Retour aux détails',
    'request.create': 'Créer la Requête',
    'request.update': 'Mettre à jour la Requête',
    'request.required': 'requis',
    'request.optional': 'optionnel',
    'request.teamsSelected': 'équipe(s) sélectionnée(s)',
    'request.noTeamFound': 'Aucune équipe trouvée',
    'request.searchTeam': 'Rechercher une équipe...',
    'request.loadingTeams': 'Chargement...',
    'request.atLeastOneTeam': 'Au moins une équipe requise',
    'request.addSuccess': 'Requête créée avec succès',
    'request.updateSuccess': 'Requête mise à jour avec succès',
    'request.deleteSuccess': 'Requête supprimée avec succès',
    'request.errorAdding': 'Veuillez sélectionner au moins un produit',
    'request.errorUpdating': 'Erreur lors de la mise à jour de la requête',
    'request.errorDeleting': 'Erreur lors de la suppression de la requête',
    'request.statusUpdated': 'Statut mis à jour avec succès',
    'request.errorUpdatingStatus': 'Erreur lors de la mise à jour du statut',
    'request.chooseNewStatus': 'Choisissez le nouveau statut pour cette requête',
    'request.selectNewStatus': 'Sélectionner un nouveau statut',
    'request.date': 'Date',
    'request.time': 'Heure',
    'request.selectDate': 'Sélectionner une date',
    // Skills
    'skills.title': 'Compétences',
    'skills.name': 'Nom de la compétence',
    'skills.description': 'Description',
    'skills.addNew': 'Nouvelle compétence',
    'skills.manage': 'Gérer les compétences des bénévoles',
    'skills.search': 'Rechercher des compétences...',
    'skills.noResults': 'Aucune compétence trouvée.',
    'skills.addSuccess': 'Compétence ajoutée avec succès',
    'skills.updateSuccess': 'Compétence mise à jour avec succès',
    'skills.deleteSuccess': 'Compétence supprimée avec succès',
    'skills.errorAdding': 'Erreur lors de l\'ajout de la compétence',
    'skills.errorUpdating': 'Erreur lors de la mise à jour de la compétence',
    'skills.errorDeleting': 'Erreur lors de la suppression de la compétence',
    // Form validation
    'validation.required': 'Ce champ est requis',
    'validation.email': 'Adresse email invalide',
    'validation.phone': 'Numéro de téléphone invalide',
    'validation.minLength': 'Minimum {min} caractères requis',
    'validation.maxLength': 'Maximum {max} caractères autorisés',
    'validation.numeric': 'Seuls les chiffres sont autorisés',
    'validation.alphanumeric': 'Seuls les lettres et chiffres sont autorisés',
    // Date and time
    'date.today': 'Aujourd\'hui',
    'date.yesterday': 'Hier',
    'date.tomorrow': 'Demain',
    'date.thisWeek': 'Cette semaine',
    'date.lastWeek': 'Semaine dernière',
    'date.nextWeek': 'Semaine prochaine',
    'date.thisMonth': 'Ce mois',
    'date.lastMonth': 'Mois dernier',
    'date.nextMonth': 'Mois prochain',
    'time.morning': 'Matin',
    'time.afternoon': 'Après-midi',
    'time.evening': 'Soir',
    'time.night': 'Nuit',
    // Days of week
    'days.monday': 'Lundi',
    'days.tuesday': 'Mardi',
    'days.wednesday': 'Mercredi',
    'days.thursday': 'Jeudi',
    'days.friday': 'Vendredi',
    'days.saturday': 'Samedi',
    'days.sunday': 'Dimanche',
    // Months
    'months.january': 'Janvier',
    'months.february': 'Février',
    'months.march': 'Mars',
    'months.april': 'Avril',
    'months.may': 'Mai',
    'months.june': 'Juin',
    'months.july': 'Juillet',
    'months.august': 'Août',
    'months.september': 'Septembre',
    'months.october': 'Octobre',
    'months.november': 'Novembre',
    'months.december': 'Décembre',
    // Conditions
    'condition.new': 'Neuf',
    'condition.excellent': 'Excellent',
    'condition.good': 'Bon',
    'condition.fair': 'Correct',
    'condition.poor': 'Mauvais',
    'condition.damaged': 'Endommagé',
    'request.list': 'Liste des Requêtes',
    'request.searchRequests': 'Rechercher des requêtes...',
    'request.deleteConfirmation': 'Cette action supprimera définitivement la requête',
  },
  en: {
    'title.all': 'Helping With Furniture',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Helping With Furniture',
    'dashboard.totalClients': 'Total Clients',
    'dashboard.activeVolunteers': 'Active Volunteers',
    'dashboard.inventoryItems': 'Inventory Items',
    'dashboard.pendingRequests': 'Pending Requests',
    'dashboard.monthlyStats': 'New Clients and Volunteers by Month',
    'dashboard.recentActivity': 'Recent Activity',
    // Common
    'common.loading': 'Loading...',
    'common.unknown': 'Unknown',
    'common.request': 'Request',
    'common.for': 'for',
    'common.status': 'Status',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.actions': 'Actions',
    'common.filters': 'Filters',
    'common.areYouSure': 'Are you sure?',
    'common.saving': 'Saving...',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.add': 'Add',
    'common.create': 'Create',
    'common.close': 'Close',
    'common.none': 'None',
    'common.all': 'All',
    'common.select': 'Select',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    'common.optional': 'optional',
    'common.required': 'required',
    'common.search': 'Search',
    'common.new': 'New',
    'common.delete': 'Delete',
    'common.total': 'Total',
    'common.active': 'Active',
    'common.completed': 'Completed',
    'common.members': 'Members',
    'common.skills': 'Skills',
    'common.id': 'ID',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.city': 'City',
    'common.adults': 'Adults',
    'common.children': 'Children',
    'common.transportation': 'Transportation',
    'common.housing': 'Housing',
    'common.origin': 'Origin',
    'common.availability': 'Availability',
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.clients': 'Clients',
    'nav.volunteers': 'Volunteers',
    'nav.teams': 'Teams',
    'nav.inventory': 'Inventory',
    'nav.categories': 'Categories',
    'nav.requests': 'Requests',
    'nav.skills': 'Skills',
    // Auth
    'auth.logout': 'Log out',
    'auth.settings': 'Settings',
    'auth.administrator': 'Administrator',
    'auth.volunteer': 'Volunteer',
    'auth.login': 'Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.signOut': 'Sign Out',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.invalidCredentials': 'Invalid credentials',
    'auth.loginSuccess': 'Login successful',
    'auth.loginError': 'Login error',
    // Headers
    'header.backToClients': 'Back to Clients',
    'header.backToVolunteers': 'Back to Volunteers',
    'header.backToInventory': 'Back to Inventory',
    'header.backToRequests': 'Back to Requests',
    'header.backToTeams': 'Back to Teams',
    'header.backHome': 'Back to Home',
    // Actions
    'actions.addClient': 'Add Client',
    'actions.addVolunteer': 'Add Volunteer',
    'actions.addInventory': 'Add Item',
    'actions.addRequest': 'Add Request',
    'actions.addTeam': 'Add Team',
    'actions.updateStatus': 'Update Status',
    'actions.cancel': 'Cancel',
    'actions.update': 'Update',
    'actions.search': 'Search',
    'actions.delete': 'Delete',
    'actions.save': 'Save',
    'actions.assign': 'Assign',
    'actions.unassign': 'Unassign',
    'actions.approve': 'Approve',
    'actions.reject': 'Reject',
    'actions.complete': 'Complete',
    'actions.schedule': 'Schedule',
    'actions.reschedule': 'Reschedule',
    'actions.export': 'Export',
    'actions.import': 'Import',
    'actions.print': 'Print',
    'actions.copy': 'Copy',
    'actions.move': 'Move',
    // Pages
    'pages.clients.title': 'Clients',
    'pages.clients.addNew': 'Add New Client',
    'pages.clients.information': 'Client Information',
    'pages.clients.manage': 'Manage client information and requests',
    'pages.volunteers.title': 'Volunteers',
    'pages.volunteers.manage': 'Manage volunteer information and assignments',
    'pages.volunteers.addNew': 'Add New Volunteer',
    'pages.volunteers.information': 'Volunteer Information',
    'pages.inventory.title': 'Inventory',
    'pages.inventory.manage': 'Manage donation items and stock levels',
    'pages.inventory.addNew': 'Add New Item',
    'pages.inventory.information': 'Item Information',
    'pages.requests.title': 'Requests',
    'pages.requests.addNew': 'New Request',
    'pages.requests.information': 'Request Details',
    'pages.requests.manage': 'Manage donation requests',
    'pages.teams.title': 'Teams',
    'pages.teams.manage': 'Manage your volunteer teams and assignments',
    'pages.teams.addNew': 'New Team',
    'pages.teams.information': 'Team Information',
    'pages.notFound.title': 'Page Not Found',
    'pages.notFound.description': 'The page you are looking for doesn\'t exist or has been moved.',
    'pages.notFound.goHome': 'Go Home',
    // Status
    'status.new': 'New',
    'status.inProgress': 'In Progress',
    'status.processing': 'Processing',
    'status.scheduled': 'Scheduled',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.draft': 'Draft',
    'status.published': 'Published',
    'status.archived': 'Archived',
    // Priority
    'priority.low': 'Low',
    'priority.medium': 'Medium',
    'priority.high': 'High',
    'priority.urgent': 'Urgent',
    // Inventory
    'inventory.list': 'Inventory List',
    'inventory.item': 'Item',
    'inventory.category': 'Category',
    'inventory.condition': 'Condition',
    'inventory.quantity': 'Quantity',
    'inventory.location': 'Location',
    'inventory.available': 'Available',
    'inventory.unavailable': 'Unavailable',
    'inventory.search': 'Search inventory...',
    'inventory.noItems': 'No items found.',
    'inventory.errorLoading': 'Failed to load inventory items',
    'inventory.itemDeleted': 'Item deleted successfully',
    'inventory.errorDeleting': 'Failed to delete item',
    'inventory.deleteConfirmation': 'This action cannot be undone. This will permanently delete the inventory item.',
    'inventory.itemAdded': 'Item added successfully',
    'inventory.itemUpdated': 'Item updated successfully',
    'inventory.errorAdding': 'Error adding item',
    'inventory.errorUpdating': 'Error updating item',
    // Categories
    'categories.manage': 'Manage inventory categories for better organization',
    'categories.list': 'Category List',
    'categories.name': 'Category Name',
    'categories.description': 'Description',
    'categories.addNew': 'New Category',
    'categories.search': 'Search categories...',
    'categories.noResults': 'No categories found.',
    'categories.errorLoading': 'Failed to load categories',
    'categories.deleted': 'Category deleted successfully',
    'categories.errorDeleting': 'Failed to delete category. It may be in use by inventory items.',
    'categories.deleteTitle': 'Delete Category',
    'categories.deleteConfirmation': 'Are you sure you want to delete this category? This action cannot be undone.',
    'categories.delete': 'Delete Category',
    'categories.information': 'Category Information',
    'categories.addDescription': 'Add a new category to organize your inventory',
    'categories.namePlaceholder': 'Enter category name',
    'categories.descriptionPlaceholder': 'Enter category description',
    'categories.addSuccess': 'Category added successfully',
    'categories.errorAdding': 'Failed to add category',
    // Client fields
    'client.firstName': 'First Name',
    'client.lastName': 'Last Name',
    'client.email': 'Email',
    'client.phone': 'Phone',
    'client.address': 'Address',
    'client.city': 'City',
    'client.postalCode': 'Postal Code',
    'client.languagesSpoken': 'Languages Spoken',
    'client.countryOfOrigin': 'Country of Origin',
    'client.statusInCanada': 'Status in Canada',
    'client.housingType': 'Housing Type',
    'client.hasTransportation': 'Has Transportation',
    'client.numberOfAdults': 'Number of Adults',
    'client.numberOfChildren': 'Number of Children',
    'client.childrenAges': 'Children\'s Ages',
    'client.referenceOrganization': 'Reference Organization',
    'client.refClient': 'Reference Client',
    'client.notes': 'Notes',
    'client.createdAt': 'Created At',
    'client.updatedAt': 'Last Updated',
    'client.addSuccess': 'Client added successfully',
    'client.updateSuccess': 'Client updated successfully',
    'client.deleteSuccess': 'Client deleted successfully',
    'client.errorAdding': 'Error adding client',
    'client.errorUpdating': 'Error updating client',
    'client.errorDeleting': 'Error deleting client',
    'client.searchClient': 'Search for a client...',
    'client.noClientFound': 'No clients found',
    'client.details': 'Client Details',
    'client.contactInformation': 'Contact Information',
    'client.householdInformation': 'Household Information',
    'client.demographics': 'Demographics',
    'client.speaksLanguages': 'Speaks',
    'client.fromCountry': 'From',
    'client.backToClients': 'Back to Clients',
    'client.editClient': 'Edit',
    'client.deleteClient': 'Delete',
    'client.directory': 'Client Directory',
    'client.searchClients': 'Search clients...',
    'client.noResults': 'No clients found',
    'client.loading': 'Loading clients...',
    'client.select': 'Select a client',
    'client.selectClient': 'Select a client...',
    // Volunteer fields
    'volunteer.firstName': 'First Name',
    'volunteer.lastName': 'Last Name',
    'volunteer.email': 'Email',
    'volunteer.phone': 'Phone',
    'volunteer.address': 'Address',
    'volunteer.city': 'City',
    'volunteer.postalCode': 'Postal Code',
    'volunteer.skills': 'Skills',
    'volunteer.availability': 'Availability',
    'volunteer.notes': 'Notes',
    'volunteer.status': 'Status',
    'volunteer.joinDate': 'Join Date',
    'volunteer.addSuccess': 'Volunteer added successfully',
    'volunteer.updateSuccess': 'Volunteer updated successfully',
    'volunteer.deleteSuccess': 'Volunteer deleted successfully',
    'volunteer.errorAdding': 'Error adding volunteer',
    'volunteer.errorUpdating': 'Error updating volunteer',
    'volunteer.errorDeleting': 'Error deleting volunteer',
    'volunteer.searchVolunteer': 'Search for a volunteer...',
    'volunteer.noVolunteerFound': 'No volunteers found',
    'volunteer.name': 'Name',
    'volunteer.noResults': 'No volunteers found',
    'volunteer.loading': 'Loading volunteers...',
    'volunteer.select': 'Select a volunteer',
    'volunteer.selectVolunteer': 'Select a volunteer...',
    // Team fields
    'team.name': 'Team Name',
    'team.description': 'Description',
    'team.members': 'Members',
    'team.leader': 'Team Leader',
    'team.skills': 'Skills',
    'team.status': 'Status',
    'team.createdAt': 'Created At',
    'team.addSuccess': 'Team added successfully',
    'team.updateSuccess': 'Team updated successfully',
    'team.deleteSuccess': 'Team deleted successfully',
    'team.errorAdding': 'Error adding team',
    'team.errorUpdating': 'Error updating team',
    'team.errorDeleting': 'Error deleting team',
    'team.totalTeams': 'Total Teams',
    'team.teamMembers': 'Team Members',
    'team.activeRequests': 'Active Requests',
    'team.completedRequests': 'Completed Requests',
    'team.list': 'Team List',
    'team.searchTeams': 'Search teams...',
    'team.teamName': 'Team Name',
    'team.newTeam': 'New Team',
    'team.noResults': 'No teams found',
    'team.loading': 'Loading teams...',
    'team.selectTeams': 'Select teams...',
    'team.searchTeam': 'Search for a team...',
    'team.teamsSelected': 'team(s) selected',
    'team.noTeamFound': 'No teams found',
    'team.atLeastOneTeam': 'At least one team required',
    // Status in Canada
    'status.permanentResident': 'Permanent Resident',
    'status.refugee': 'Refugee',
    'status.studentVisa': 'Student Visa',
    'status.temporaryResident': 'Temporary Resident',
    // Housing types
    'housing.apartment': 'Apartment',
    'housing.house': 'House',
    'housing.townhouse': 'Townhouse',
    'housing.basementApartment': 'Basement Apartment',
    'housing.temporary': 'Temporary',
    // Request fields
    'request.client': 'Client',
    'request.team': 'Team',
    'request.teams': 'Teams',
    'request.volunteer': 'Volunteer',
    'request.priority': 'Priority',
    'request.status': 'Status',
    'request.location': 'Delivery Address',
    'request.description': 'Description',
    'request.details': 'Request Details',
    'request.products': 'Product Selection',
    'request.selectTeams': 'Select teams...',
    'request.selectVolunteer': 'Select a volunteer...',
    'request.selectClient': 'Select a client...',
    'request.selectPriority': 'Select a priority',
    'request.selectStatus': 'Select a status',
    'request.enterLocation': 'Enter address',
    'request.enterDescription': 'Enter request details',
    'request.continueProducts': 'Continue to product selection',
    'request.backToDetails': 'Back to details',
    'request.create': 'Create Request',
    'request.update': 'Update Request',
    'request.required': 'required',
    'request.optional': 'optional',
    'request.teamsSelected': 'team(s) selected',
    'request.noTeamFound': 'No teams found',
    'request.searchTeam': 'Search for a team...',
    'request.loadingTeams': 'Loading...',
    'request.atLeastOneTeam': 'At least one team required',
    'request.addSuccess': 'Request created successfully',
    'request.updateSuccess': 'Request updated successfully',
    'request.deleteSuccess': 'Request deleted successfully',
    'request.errorAdding': 'Please select at least one product',
    'request.errorUpdating': 'Error updating request',
    'request.errorDeleting': 'Error deleting request',
    'request.statusUpdated': 'Status updated successfully',
    'request.errorUpdatingStatus': 'Error updating status',
    'request.chooseNewStatus': 'Choose the new status for this request',
    'request.selectNewStatus': 'Select a new status',
    'request.date': 'Date',
    'request.time': 'Time',
    'request.selectDate': 'Select a date',
    // Skills
    'skills.title': 'Skills',
    'skills.name': 'Skill Name',
    'skills.description': 'Description',
    'skills.addNew': 'New Skill',
    'skills.manage': 'Manage volunteer skills',
    'skills.search': 'Search skills...',
    'skills.noResults': 'No skills found.',
    'skills.addSuccess': 'Skill added successfully',
    'skills.updateSuccess': 'Skill updated successfully',
    'skills.deleteSuccess': 'Skill deleted successfully',
    'skills.errorAdding': 'Error adding skill',
    'skills.errorUpdating': 'Error updating skill',
    'skills.errorDeleting': 'Error deleting skill',
    // Form validation
    'validation.required': 'This field is required',
    'validation.email': 'Invalid email address',
    'validation.phone': 'Invalid phone number',
    'validation.minLength': 'Minimum {min} characters required',
    'validation.maxLength': 'Maximum {max} characters allowed',
    'validation.numeric': 'Only numbers are allowed',
    'validation.alphanumeric': 'Only letters and numbers are allowed',
    // Date and time
    'date.today': 'Today',
    'date.yesterday': 'Yesterday',
    'date.tomorrow': 'Tomorrow',
    'date.thisWeek': 'This week',
    'date.lastWeek': 'Last week',
    'date.nextWeek': 'Next week',
    'date.thisMonth': 'This month',
    'date.lastMonth': 'Last month',
    'date.nextMonth': 'Next month',
    'time.morning': 'Morning',
    'time.afternoon': 'Afternoon',
    'time.evening': 'Evening',
    'time.night': 'Night',
    // Days of week
    'days.monday': 'Monday',
    'days.tuesday': 'Tuesday',
    'days.wednesday': 'Wednesday',
    'days.thursday': 'Thursday',
    'days.friday': 'Friday',
    'days.saturday': 'Saturday',
    'days.sunday': 'Sunday',
    // Months
    'months.january': 'January',
    'months.february': 'February',
    'months.march': 'March',
    'months.april': 'April',
    'months.may': 'May',
    'months.june': 'June',
    'months.july': 'July',
    'months.august': 'August',
    'months.september': 'September',
    'months.october': 'October',
    'months.november': 'November',
    'months.december': 'December',
    // Conditions
    'condition.new': 'New',
    'condition.excellent': 'Excellent',
    'condition.good': 'Good',
    'condition.fair': 'Fair',
    'condition.poor': 'Poor',
    'condition.damaged': 'Damaged',
    'request.list': 'Request List',
    'request.searchRequests': 'Search requests...',
    'request.deleteConfirmation': 'This action will permanently delete the request',
  }
};

export const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Get saved language from localStorage or default to 'fr'
    const savedLanguage = localStorage.getItem('language');
    return (savedLanguage as Language) || 'fr';
  });

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const currentTranslations = translations[language] as Record<string, string>;
    return currentTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
