export const countries = [
  { code: 'AF', name: { fr: 'Afghanistan', en: 'Afghanistan' } },
  { code: 'AL', name: { fr: 'Albanie', en: 'Albania' } },
  { code: 'DZ', name: { fr: 'Algérie', en: 'Algeria' } },
  { code: 'AD', name: { fr: 'Andorre', en: 'Andorra' } },
  { code: 'AO', name: { fr: 'Angola', en: 'Angola' } },
  { code: 'AR', name: { fr: 'Argentine', en: 'Argentina' } },
  { code: 'AM', name: { fr: 'Arménie', en: 'Armenia' } },
  { code: 'AU', name: { fr: 'Australie', en: 'Australia' } },
  { code: 'AT', name: { fr: 'Autriche', en: 'Austria' } },
  { code: 'AZ', name: { fr: 'Azerbaïdjan', en: 'Azerbaijan' } },
  { code: 'BD', name: { fr: 'Bangladesh', en: 'Bangladesh' } },
  { code: 'BE', name: { fr: 'Belgique', en: 'Belgium' } },
  { code: 'BZ', name: { fr: 'Belize', en: 'Belize' } },
  { code: 'BJ', name: { fr: 'Bénin', en: 'Benin' } },
  { code: 'BO', name: { fr: 'Bolivie', en: 'Bolivia' } },
  { code: 'BA', name: { fr: 'Bosnie-Herzégovine', en: 'Bosnia and Herzegovina' } },
  { code: 'BR', name: { fr: 'Brésil', en: 'Brazil' } },
  { code: 'BG', name: { fr: 'Bulgarie', en: 'Bulgaria' } },
  { code: 'BF', name: { fr: 'Burkina Faso', en: 'Burkina Faso' } },
  { code: 'BI', name: { fr: 'Burundi', en: 'Burundi' } },
  { code: 'KH', name: { fr: 'Cambodge', en: 'Cambodia' } },
  { code: 'CM', name: { fr: 'Cameroun', en: 'Cameroon' } },
  { code: 'CA', name: { fr: 'Canada', en: 'Canada' } },
  { code: 'CF', name: { fr: 'République centrafricaine', en: 'Central African Republic' } },
  { code: 'TD', name: { fr: 'Tchad', en: 'Chad' } },
  { code: 'CL', name: { fr: 'Chili', en: 'Chile' } },
  { code: 'CN', name: { fr: 'Chine', en: 'China' } },
  { code: 'CO', name: { fr: 'Colombie', en: 'Colombia' } },
  { code: 'CG', name: { fr: 'Congo', en: 'Congo' } },
  { code: 'CD', name: { fr: 'République démocratique du Congo', en: 'Democratic Republic of the Congo' } },
  { code: 'CR', name: { fr: 'Costa Rica', en: 'Costa Rica' } },
  { code: 'HR', name: { fr: 'Croatie', en: 'Croatia' } },
  { code: 'CU', name: { fr: 'Cuba', en: 'Cuba' } },
  { code: 'CZ', name: { fr: 'République tchèque', en: 'Czech Republic' } },
  { code: 'DK', name: { fr: 'Danemark', en: 'Denmark' } },
  { code: 'EC', name: { fr: 'Équateur', en: 'Ecuador' } },
  { code: 'EG', name: { fr: 'Égypte', en: 'Egypt' } },
  { code: 'ER', name: { fr: 'Érythrée', en: 'Eritrea' } },
  { code: 'EE', name: { fr: 'Estonie', en: 'Estonia' } },
  { code: 'ET', name: { fr: 'Éthiopie', en: 'Ethiopia' } },
  { code: 'FI', name: { fr: 'Finlande', en: 'Finland' } },
  { code: 'FR', name: { fr: 'France', en: 'France' } },
  { code: 'GA', name: { fr: 'Gabon', en: 'Gabon' } },
  { code: 'GM', name: { fr: 'Gambie', en: 'Gambia' } },
  { code: 'GE', name: { fr: 'Géorgie', en: 'Georgia' } },
  { code: 'DE', name: { fr: 'Allemagne', en: 'Germany' } },
  { code: 'GH', name: { fr: 'Ghana', en: 'Ghana' } },
  { code: 'GR', name: { fr: 'Grèce', en: 'Greece' } },
  { code: 'GT', name: { fr: 'Guatemala', en: 'Guatemala' } },
  { code: 'GN', name: { fr: 'Guinée', en: 'Guinea' } },
  { code: 'HT', name: { fr: 'Haïti', en: 'Haiti' } },
  { code: 'HN', name: { fr: 'Honduras', en: 'Honduras' } },
  { code: 'HU', name: { fr: 'Hongrie', en: 'Hungary' } },
  { code: 'IS', name: { fr: 'Islande', en: 'Iceland' } },
  { code: 'IN', name: { fr: 'Inde', en: 'India' } },
  { code: 'ID', name: { fr: 'Indonésie', en: 'Indonesia' } },
  { code: 'IR', name: { fr: 'Iran', en: 'Iran' } },
  { code: 'IQ', name: { fr: 'Irak', en: 'Iraq' } },
  { code: 'IE', name: { fr: 'Irlande', en: 'Ireland' } },
  { code: 'IL', name: { fr: 'Israël', en: 'Israel' } },
  { code: 'IT', name: { fr: 'Italie', en: 'Italy' } },
  { code: 'JM', name: { fr: 'Jamaïque', en: 'Jamaica' } },
  { code: 'JP', name: { fr: 'Japon', en: 'Japan' } },
  { code: 'JO', name: { fr: 'Jordanie', en: 'Jordan' } },
  { code: 'KZ', name: { fr: 'Kazakhstan', en: 'Kazakhstan' } },
  { code: 'KE', name: { fr: 'Kenya', en: 'Kenya' } },
  { code: 'KR', name: { fr: 'Corée du Sud', en: 'South Korea' } },
  { code: 'KW', name: { fr: 'Koweït', en: 'Kuwait' } },
  { code: 'LB', name: { fr: 'Liban', en: 'Lebanon' } },
  { code: 'LR', name: { fr: 'Libéria', en: 'Liberia' } },
  { code: 'LY', name: { fr: 'Libye', en: 'Libya' } },
  { code: 'LT', name: { fr: 'Lituanie', en: 'Lithuania' } },
  { code: 'LU', name: { fr: 'Luxembourg', en: 'Luxembourg' } },
  { code: 'MG', name: { fr: 'Madagascar', en: 'Madagascar' } },
  { code: 'MW', name: { fr: 'Malawi', en: 'Malawi' } },
  { code: 'MY', name: { fr: 'Malaisie', en: 'Malaysia' } },
  { code: 'ML', name: { fr: 'Mali', en: 'Mali' } },
  { code: 'MA', name: { fr: 'Maroc', en: 'Morocco' } },
  { code: 'MX', name: { fr: 'Mexique', en: 'Mexico' } },
  { code: 'MD', name: { fr: 'Moldavie', en: 'Moldova' } },
  { code: 'MN', name: { fr: 'Mongolie', en: 'Mongolia' } },
  { code: 'ME', name: { fr: 'Monténégro', en: 'Montenegro' } },
  { code: 'MZ', name: { fr: 'Mozambique', en: 'Mozambique' } },
  { code: 'MM', name: { fr: 'Myanmar', en: 'Myanmar' } },
  { code: 'NA', name: { fr: 'Namibie', en: 'Namibia' } },
  { code: 'NP', name: { fr: 'Népal', en: 'Nepal' } },
  { code: 'NL', name: { fr: 'Pays-Bas', en: 'Netherlands' } },
  { code: 'NZ', name: { fr: 'Nouvelle-Zélande', en: 'New Zealand' } },
  { code: 'NI', name: { fr: 'Nicaragua', en: 'Nicaragua' } },
  { code: 'NE', name: { fr: 'Niger', en: 'Niger' } },
  { code: 'NG', name: { fr: 'Nigeria', en: 'Nigeria' } },
  { code: 'NO', name: { fr: 'Norvège', en: 'Norway' } },
  { code: 'PK', name: { fr: 'Pakistan', en: 'Pakistan' } },
  { code: 'PA', name: { fr: 'Panama', en: 'Panama' } },
  { code: 'PY', name: { fr: 'Paraguay', en: 'Paraguay' } },
  { code: 'PE', name: { fr: 'Pérou', en: 'Peru' } },
  { code: 'PH', name: { fr: 'Philippines', en: 'Philippines' } },
  { code: 'PL', name: { fr: 'Pologne', en: 'Poland' } },
  { code: 'PT', name: { fr: 'Portugal', en: 'Portugal' } },
  { code: 'RO', name: { fr: 'Roumanie', en: 'Romania' } },
  { code: 'RU', name: { fr: 'Russie', en: 'Russia' } },
  { code: 'RW', name: { fr: 'Rwanda', en: 'Rwanda' } },
  { code: 'SA', name: { fr: 'Arabie Saoudite', en: 'Saudi Arabia' } },
  { code: 'SN', name: { fr: 'Sénégal', en: 'Senegal' } },
  { code: 'RS', name: { fr: 'Serbie', en: 'Serbia' } },
  { code: 'SL', name: { fr: 'Sierra Leone', en: 'Sierra Leone' } },
  { code: 'SG', name: { fr: 'Singapour', en: 'Singapore' } },
  { code: 'SK', name: { fr: 'Slovaquie', en: 'Slovakia' } },
  { code: 'SI', name: { fr: 'Slovénie', en: 'Slovenia' } },
  { code: 'SO', name: { fr: 'Somalie', en: 'Somalia' } },
  { code: 'ZA', name: { fr: 'Afrique du Sud', en: 'South Africa' } },
  { code: 'ES', name: { fr: 'Espagne', en: 'Spain' } },
  { code: 'LK', name: { fr: 'Sri Lanka', en: 'Sri Lanka' } },
  { code: 'SD', name: { fr: 'Soudan', en: 'Sudan' } },
  { code: 'SE', name: { fr: 'Suède', en: 'Sweden' } },
  { code: 'CH', name: { fr: 'Suisse', en: 'Switzerland' } },
  { code: 'SY', name: { fr: 'Syrie', en: 'Syria' } },
  { code: 'TW', name: { fr: 'Taïwan', en: 'Taiwan' } },
  { code: 'TJ', name: { fr: 'Tadjikistan', en: 'Tajikistan' } },
  { code: 'TZ', name: { fr: 'Tanzanie', en: 'Tanzania' } },
  { code: 'TH', name: { fr: 'Thaïlande', en: 'Thailand' } },
  { code: 'TG', name: { fr: 'Togo', en: 'Togo' } },
  { code: 'TN', name: { fr: 'Tunisie', en: 'Tunisia' } },
  { code: 'TR', name: { fr: 'Turquie', en: 'Turkey' } },
  { code: 'TM', name: { fr: 'Turkménistan', en: 'Turkmenistan' } },
  { code: 'UG', name: { fr: 'Ouganda', en: 'Uganda' } },
  { code: 'UA', name: { fr: 'Ukraine', en: 'Ukraine' } },
  { code: 'AE', name: { fr: 'Émirats arabes unis', en: 'United Arab Emirates' } },
  { code: 'GB', name: { fr: 'Royaume-Uni', en: 'United Kingdom' } },
  { code: 'US', name: { fr: 'États-Unis', en: 'United States' } },
  { code: 'UY', name: { fr: 'Uruguay', en: 'Uruguay' } },
  { code: 'UZ', name: { fr: 'Ouzbékistan', en: 'Uzbekistan' } },
  { code: 'VE', name: { fr: 'Venezuela', en: 'Venezuela' } },
  { code: 'VN', name: { fr: 'Vietnam', en: 'Vietnam' } },
  { code: 'YE', name: { fr: 'Yémen', en: 'Yemen' } },
  { code: 'ZM', name: { fr: 'Zambie', en: 'Zambia' } },
  { code: 'ZW', name: { fr: 'Zimbabwe', en: 'Zimbabwe' } }
];

export const languages = [
  { code: 'ar', name: { fr: 'Arabe', en: 'Arabic' } },
  { code: 'en', name: { fr: 'Anglais', en: 'English' } },
  { code: 'fr', name: { fr: 'Français', en: 'French' } },
  { code: 'es', name: { fr: 'Espagnol', en: 'Spanish' } },
  { code: 'pt', name: { fr: 'Portugais', en: 'Portuguese' } },
  { code: 'de', name: { fr: 'Allemand', en: 'German' } },
  { code: 'it', name: { fr: 'Italien', en: 'Italian' } },
  { code: 'ru', name: { fr: 'Russe', en: 'Russian' } },
  { code: 'zh', name: { fr: 'Chinois', en: 'Chinese' } },
  { code: 'ja', name: { fr: 'Japonais', en: 'Japanese' } },
  { code: 'ko', name: { fr: 'Coréen', en: 'Korean' } },
  { code: 'hi', name: { fr: 'Hindi', en: 'Hindi' } },
  { code: 'bn', name: { fr: 'Bengali', en: 'Bengali' } },
  { code: 'ur', name: { fr: 'Ourdou', en: 'Urdu' } },
  { code: 'fa', name: { fr: 'Persan', en: 'Persian' } },
  { code: 'tr', name: { fr: 'Turc', en: 'Turkish' } },
  { code: 'pl', name: { fr: 'Polonais', en: 'Polish' } },
  { code: 'nl', name: { fr: 'Néerlandais', en: 'Dutch' } },
  { code: 'sv', name: { fr: 'Suédois', en: 'Swedish' } },
  { code: 'da', name: { fr: 'Danois', en: 'Danish' } },
  { code: 'no', name: { fr: 'Norvégien', en: 'Norwegian' } },
  { code: 'fi', name: { fr: 'Finnois', en: 'Finnish' } },
  { code: 'he', name: { fr: 'Hébreu', en: 'Hebrew' } },
  { code: 'th', name: { fr: 'Thaï', en: 'Thai' } },
  { code: 'vi', name: { fr: 'Vietnamien', en: 'Vietnamese' } },
  { code: 'ms', name: { fr: 'Malais', en: 'Malay' } },
  { code: 'id', name: { fr: 'Indonésien', en: 'Indonesian' } },
  { code: 'tl', name: { fr: 'Tagalog', en: 'Tagalog' } },
  { code: 'sw', name: { fr: 'Swahili', en: 'Swahili' } },
  { code: 'am', name: { fr: 'Amharique', en: 'Amharic' } },
  { code: 'yo', name: { fr: 'Yoruba', en: 'Yoruba' } },
  { code: 'ig', name: { fr: 'Igbo', en: 'Igbo' } },
  { code: 'ha', name: { fr: 'Haoussa', en: 'Hausa' } }
];