// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eswdgbcqmktyljnkjvuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzd2RnYmNxbWt0eWxqbmtqdnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTIzOTMsImV4cCI6MjA2MDU2ODM5M30.V1QKwiezZ3OKSlyexzFZ4Haw2uxPA4vQr-7RX7egkzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);